server:
    port: 4006
database:
    postgres:
        user: ""
        password: ""
        database_name: ""
        ip: ""
    redis:
email:
    service:
    email:
    password:
jwt:
    secret: 
    time: